SRC=./src
OUT=./out
BOOST_HOME=/mnt/work/software/develop/dependences/boost_155
#c++ -I ${BOOST_HOME}/include main.cpp -o example
all:
	@g++ -I ${BOOST_HOME}/include ${SRC}/main.cpp -o ${OUT}/tst 
run:
	@${OUT}/tst