// Copyright (c) 2016 The Foundry Visionmongers Ltd.
#ifndef KATANA_FNDEFAULTATTRIBUTEPRODUCER_FNDEFAULTATTRIBUTEPRODUCERAPI_H_
#define KATANA_FNDEFAULTATTRIBUTEPRODUCER_FNDEFAULTATTRIBUTEPRODUCERAPI_H_

#if defined(_WIN32)
#  if defined(FNDEFAULTATTRIBUTEPRODUCER_APIEXPORT)
#    define FNDEFAULTATTRIBUTEPRODUCER_API __declspec(dllexport)
#  elif !defined(FNDEFAULTATTRIBUTEPRODUCER_STATIC)
#    define FNDEFAULTATTRIBUTEPRODUCER_API __declspec(dllimport)
#  else
#    define FNDEFAULTATTRIBUTEPRODUCER_API
#  endif  // FNDEFAULTATTRIBUTEPRODUCER_APIEXPORT

#elif defined(FNDEFAULTATTRIBUTEPRODUCER_APIEXPORT)
#  define FNDEFAULTATTRIBUTEPRODUCER_API __attribute__((visibility("default")))
#else
#  define FNDEFAULTATTRIBUTEPRODUCER_API
#endif  // _WIN32

#endif  // KATANA_FNDEFAULTATTRIBUTEPRODUCER_FNDEFAULTATTRIBUTEPRODUCERAPI_H_
