#!/usr/bin/env bash
# Katana launcher script.

export RMANTREE=/opt/pixar/RenderManProServer-21.4
export KATANA_RESOURCES=/opt/pixar/RenderManForKatana-21.4-katana2.5/plugins/Resources/PRMan21:${KATANA_RESOURCES}
export RMAN_SHADERPATH=${RMANTREE}/lib/shaders:${RMAN_SHADERPATH}
export RMAN_RIXPLUGINPATH=${RMANTREE}/lib/plugins:${RMAN_RIXPLUGINPATH}
export DEFAULT_RENDERER=prman

# Determine the KATANA installation
if [ -z $KATANA_ROOT ];then
    export KATANA_ROOT="/mnt/work/software/katana/katana2.5v5"
fi

if [ ! -x "${KATANA_ROOT}/bin/katanaBin" ]
then
    echo "ERROR: Unable to find 'bin/katanaBin' in the KATANA installation directory (${KATANA_ROOT})" 1>&2
    exit 1
fi

# ZLib
# Add ZLib sub-folder to LD_LIBRARY_PATH only if KATANA_USE_INTERNAL_ZLIB is set
if [ -n "${KATANA_USE_INTERNAL_ZLIB+set}" ]
then
    export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/ZLib:${LD_LIBRARY_PATH}"
fi

# Geolib3 internal libraries.
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/CEL:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/ExpressionMath:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnAssetHost:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnAttribute:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnConfiguration:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnGeolib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnGeolibProducers:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnGeolibServices:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnGeolibServicesHost:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/FnRenderServices:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/PyCEL:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/PyFnAttribute:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/PyFnConfiguration:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/PyFnGeolib:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/PyFnGeolibProducers:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/PyFnGeolibServices:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/PyFnScenegraphAttr:${LD_LIBRARY_PATH}"
export LD_LIBRARY_PATH="${KATANA_ROOT}/bin/Geolib3/internal/ResolutionTable:${LD_LIBRARY_PATH}"

exec "${KATANA_ROOT}/bin/katanaBin" "$@"
