#!/usr/bin/env bash
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo "+                                                                 +"
echo "+  ============== Light Chaser Animation Katana RS==============  +"
echo "+                                                                 +"
echo "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
echo
export LCTOOLSET=/home/xukai/Git/git_repo/lcatools
export LCA_DEVKTN_PATH=/home/xukai/Git/git_repo/katana
export LCA_DEVMY_PATH=/home/xukai/Git/git_repo/maya

## launch katana
source "${LCA_DEVKTN_PATH}/launcher/env_config/redshift_dev_v25.sh"
exec "${LCA_SOFTWARE_PATH}/katana/katana2.5v5/katana"