#!/usr/bin/env bash

## clone oslShaders repository
#cd /home/xukai/Git/git_repo/
#git clone ssh://git@10.0.0.6/home/git/repositories/oslShaders.git

## set title
echo
echo -e "==========+ '\033[0;31m'Shader Dev'\033[0m' +=========="
echo

## set environment variable
export LCA_OSLSHD_PATH=/home/xukai/Git/git_repo/
export LCA_DEVKTN_PATH=/home/xukai/Git/git_repo/katana
## launch katana
/home/xukai/Git/git_repo/lca_rez/launchers/pws/linux/katana