// Copyright (c) 2016 The Foundry Visionmongers Ltd.
#ifndef KATANA_FNRENDEROUTPUTLOCATION_FNRENDEROUTPUTLOCATIONAPI_H_
#define KATANA_FNRENDEROUTPUTLOCATION_FNRENDEROUTPUTLOCATIONAPI_H_

#if defined(_WIN32)
#  if defined(FNRENDEROUTPUTLOCATION_APIEXPORT)
#    define FNRENDEROUTPUTLOCATION_API __declspec(dllexport)
#  elif !defined(FNRENDEROUTPUTLOCATION_STATIC)
#    define FNRENDEROUTPUTLOCATION_API __declspec(dllimport)
#  else
#    define FNRENDEROUTPUTLOCATION_API
#  endif  // FNRENDEROUTPUTLOCATION_APIEXPORT

#elif defined(FNRENDEROUTPUTLOCATION_APIEXPORT)
#  define FNRENDEROUTPUTLOCATION_API __attribute__((visibility("default")))
#else
#  define FNRENDEROUTPUTLOCATION_API
#endif  // _WIN32

#endif  // KATANA_FNRENDEROUTPUTLOCATION_FNRENDEROUTPUTLOCATIONAPI_H_
