#!/usr/bin/env bash
echo "===+ Katana A5 +==="


##Enviroment Variable For Developing
export LCTOOLSET=/mnt/utility/toolset

export LC_PROJ_PATH=/mnt/proj/projects

export KATANA_HOME=/mnt/work/software/katana/katana2.5v5

export MAYA_HOME=/mnt/usr/autodesk/maya2017

export LCA_DEVKTN_PATH=/home/xukai/Git/git_repo/katana

export LCA_DEVMY_PATH=/mnt/work/software/develop/maya

export LCA_SOFTWARE_PATH=/mnt/work/software

##in case too many open files
ulimit -HSn 65536 &>/dev/null


# ------common env
export LGT_RESOURCE=/mnt/proj/resource/lgt


# ------common path
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:/usr/local/rv/rv-Linux-x86-64-4.0.10/bin:$PATH"
export LUA_PATH="${LCTOOLSET}/applications/katana_v2/Lua_scripts/?.lua"
export PYTHONPATH="${LCTOOLSET}/applications/katana/Scripts:${LGT_RESOURCE}/katana/Scripts:${LCTOOLSET}/tools:/mnt/proj/software/lib/lib64/python2.6/site-packages:/mnt/proj/software/muster8.5.7-sdk/libs/linux64/python27:${LCTOOLSET}/lib:$PYTHONPATH"
export LD_LIBRARY_PATH="${KTOA_HOME}/bin:${LCA_SOFTWARE_PATH}/muster8.5.7:$LD_LIBRARY_PATH"


# ------katana env
export KATANA_RESOURCES=${LCA_DEVKTN_PATH}/resource/2.5:$KATANA_RESOURCES
export KATANA_RESOURCES=$LGT_RESOURCE/katana_v2:$KATANA_RESOURCES
export KATANA_RESOURCES=${LCTOOLSET}/applications/katana_v2:$KATANA_RESOURCES
export KATANA_RESOURCES=${KATANA_HOME}/plugins/Resources/Examples:$KATANA_RESOURCES


# ------shotgun
export PYTHONPATH="/mnt/work/soft/tank/studio/install/core/python:${PYTHONPATH}"
export KATANA_RESOURCES=${TANK_KATANA_RESOURCES}:${KATANA_RESOURCES}


# ------ktoa
export DEFAULT_RENDERER=arnold
export solidangle_LICENSE=6053@10.0.0.5
export KTOA_HOME=${LCA_DEVKTN_PATH}/arnold/ktoa-2.0.3.1-kat2.5
export ARNOLD_PLUGIN_PATH=${LCA_DEVKTN_PATH}/shader/5.x/lcaShaders:$ARNOLD_PLUGIN_PATH
export ARNOLD_SHADERLIB_PATH=${LCA_DEVKTN_PATH}/shader/5.x/alShaders:$ARNOLD_SHADERLIB_PATH
export ARNOLD_SHADERLIB_PATH=${LCA_DEVKTN_PATH}/shader/5.x/oslShaders:$ARNOLD_SHADERLIB_PATH
export KATANA_RESOURCES=${KTOA_HOME}:$KATANA_RESOURCES
export KATANA_TAGLINE="LCA With KtoA and Arnold"

# ------xgen procedural
export MAYA_PATH=${MAYA_HOME}
export MTOA_PATH=${LCA_DEVMY_PATH}/arnold/mtoa-2.0.2.2-2017
export LD_LIBRARY_PATH=${MAYA_PATH}/plug-ins/xgen/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${MAYA_PATH}/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${MTOA_PATH}/procedurals:${LD_LIBRARY_PATH}
export XGEN_LOCATION=${MAYA_PATH}/plug-ins/xgen/
export XGEN_CONFIG_PATH=${MAYA_PATH}/plug-ins/xgen/


# ------yeti procedural
export YETI_HOME=${LCA_DEVMY_PATH}/yeti/yeti-v2.2.0-2017
export PATH=$YETI_HOME/bin:$PATH
export peregrinel_LICENSE=5059@10.0.0.5


# boost
export LD_LIBRARY_PATH=${LCA_SOFTWARE_PATH}/lib/shared_libraries/boost_1.56:${LD_LIBRARY_PATH}
# OpenEXR
export LD_LIBRARY_PATH=${LCA_SOFTWARE_PATH}/lib/shared_libraries/openexrlib-2.2:${LD_LIBRARY_PATH}
# OpenVDB
export LD_LIBRARY_PATH=${LCA_SOFTWARE_PATH}/lib/OpenVDB/lib:/mnt/usr/hfs15/dsolib:${LD_LIBRARY_PATH}


## launch katana

exec "/opt/katana/katana2.5v5/katana"