# ********************************************************************
# This file contains copyrighted work from The Foundry,
# Sony Pictures Imageworks and Solid Angle, is intended for
# Katana and Solid Angle customers, and is not for distribution
# outside the terms of the corresponding EULA(s).
# ********************************************************************
#
# See README for instructions on how to use this Makefile
#

all:
	cd ArnoldPlugin; make
	cd ScenegraphLocationDelegatePlugins; make

clean:
	cd ArnoldPlugin; make clean
	cd ScenegraphLocationDelegatePlugins; make clean

