// Copyright (c) 2016 The Foundry Visionmongers Ltd.
#ifndef KATANA_FNATTRIBUTEMODIFIER_FNATTRIBUTEMODIFIERAPI_H_
#define KATANA_FNATTRIBUTEMODIFIER_FNATTRIBUTEMODIFIERAPI_H_

#if defined(_WIN32)
#  if defined(FNATTRIBUTEMODIFIER_APIEXPORT)
#    define FNATTRIBUTEMODIFIER_API __declspec(dllexport)
#  elif !defined(FNATTRIBUTEMODIFIER_STATIC)
#    define FNATTRIBUTEMODIFIER_API __declspec(dllimport)
#  else
#    define FNATTRIBUTEMODIFIER_API
#  endif  // FNATTRIBUTEMODIFIER_APIEXPORT

#elif defined(FNATTRIBUTEMODIFIER_APIEXPORT)
#  define FNATTRIBUTEMODIFIER_API __attribute__((visibility("default")))
#else
#  define FNATTRIBUTEMODIFIER_API
#endif  // _WIN32

#endif  // KATANA_FNATTRIBUTEMODIFIER_FNATTRIBUTEMODIFIERAPI_H_
