#ifndef KATANA_PLUGINAPI_FNPLATFORM_INTERNAL_PORTABILITY_H_
#define KATANA_PLUGINAPI_FNPLATFORM_INTERNAL_PORTABILITY_H_

#ifndef FNKAT_DEPRECATED
#if defined(__GNUC__)
#define FNKAT_DEPRECATED __attribute__((__deprecated__))
#elif defined(_MSC_VER)
#define FNKAT_DEPRECATED __declspec(deprecated)
#else
#define FNKAT_DEPRECATED
#endif
#endif  // FNKAT_DEPRECATED

#endif  // KATANA_PLUGINAPI_FNPLATFORM_INTERNAL_PORTABILITY_H_
