@ECHO OFF
SET REPOSITORYFOLDER="%CD%"
SET PROJECTFOLDER="%~DP0"

SET HOUDINIFOLDER="%PROJECTFOLDER%\Houdini"
IF EXIST HOUDINIFOLDER (
RMDIR HOUDINIFOLDER /S /Q
XCOPY "%REPOSITORYFOLDER%\Houdini" HOUDINIFOLDER /i
) ELSE (
XCOPY "%REPOSITORYFOLDER%\Houdini" HOUDINIFOLDER /i
)

SET HDAFOLDER="%PROJECTFOLDER%\Content\HDA"
IF EXIST HDAFOLDER (
RMDIR HDAFOLDER /S /Q
XCOPY "%REPOSITORYFOLDER%\Content\HDA" HDAFOLDER /i
) ELSE (
XCOPY "%REPOSITORYFOLDER%\Content\HDA" HDAFOLDER /i
)

SET HEFOLDER="%PROJECTFOLDER%\Content\HoudiniEngine"
IF EXIST HEFOLDER (
RMDIR HEFOLDER /S /Q
XCOPY "%REPOSITORYFOLDER%\Content\HoudiniEngine" HEFOLDER /i
) ELSE (
XCOPY "%REPOSITORYFOLDER%\Content\HoudiniEngine" HEFOLDER /i
)

SET FALCONFOLDER="%PROJECTFOLDER%\Content\Falcon"
IF EXIST FALCONFOLDER (
RMDIR FALCONFOLDER /S /Q
XCOPY "%REPOSITORYFOLDER%\Content\Falcon" FALCONFOLDER /i
) ELSE (
XCOPY "%REPOSITORYFOLDER%\Content\Falcon" FALCONFOLDER /i
)