// Copyright (c) 2016 The Foundry Visionmongers Ltd.
#ifndef KATANA_FNSCENEGRAPHGENERATOR_FNSCENEGRAPHGENERATORAPI_H_
#define KATANA_FNSCENEGRAPHGENERATOR_FNSCENEGRAPHGENERATORAPI_H_

#if defined(_WIN32)
#  if defined(FNSCENEGRAPHGENERATOR_APIEXPORT)
#    define FNSCENEGRAPHGENERATOR_API __declspec(dllexport)
#  elif !defined(FNSCENEGRAPHGENERATOR_STATIC)
#    define FNSCENEGRAPHGENERATOR_API __declspec(dllimport)
#  else
#    define FNSCENEGRAPHGENERATOR_API
#  endif  // FNSCENEGRAPHGENERATOR_APIEXPORT

#elif defined(FNSCENEGRAPHGENERATOR_APIEXPORT)
#  define FNSCENEGRAPHGENERATOR_API __attribute__((visibility("default")))
#else
#  define FNSCENEGRAPHGENERATOR_API
#endif  // _WIN32

#endif  // KATANA_FNSCENEGRAPHGENERATOR_FNSCENEGRAPHGENERATORAPI_H_
