
all:
	python /home/xukai/Documents/KT_Libs/pyuic/uic/pyuic.py -x submit_ui_new.ui -o submit_ui.py 
in:
	@echo "Install file..."
	cp -f submit_ui.py /home/xukai/Git/git_repo/lcatools/tools/lgt/submit_render_muster