#!/usr/bin/env bash

# ------systrm setting
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi
PS1='\[\e[1;32m\][\t]\[\e[m\]\[\e[1;31m\]\u\[\e[m\]\[\e[1;33m\]@\[\e[m\]\[\e[1;35m\]\H\[\e[m\]:\[\e[1;34m\]\w\[\e[m\]\[\e[1;32m\]\$\[\e[m\] '
HISTTIMEFORMAT="[`whoami`]%F %T: "

# ------common env
export LC_PROJ_PATH=/mnt/proj/projects
export KATANA_HOME=/mnt/work/software/katana/katana2.5v5
export MAYA_HOME=/mnt/usr/autodesk/maya2017
export LCA_DEVKTN_PATH=/mnt/work/software/develop/katana
export LCA_DEVMY_PATH=/mnt/work/software/develop/maya
export LCA_DEVUSD_PATH=/mnt/work/software/develop/usd
export LCA_SOFTWARE_PATH=/mnt/work/software
export LCTOOLSET=/mnt/utility/toolset
# export LCADEVLIB="/mnt/work/software/lib"
# export PYTHONPATH="$LCTOOLSET/lib:$LCTOOLSET/lib/3rd_party:$LCADEVLIB/lib64/python2.7/site-packages:$LCADEVLIB/lib64/python2.6/site-packages:$LCTOOLSET/tools:$PYTHONPATH"
# export LD_LIBRARY_PATH="$LCADEVLIB/lib:$LCADEVLIB/ilmbase1.6/lib:$LD_LIBRARY_PATH"


# ------rv and shotgun
# export RV_PATHSWAP_ROOT=/mnt/proj
# export SHOTGUN_PLUGIN_PROTOCOL_RESTRICTION="http"
# export SHOTGUN_PLUGIN_DOMAIN_RESTRICTION="shotgun.zhuiguang.com"
# export PATH=/usr/local/rv/rv-Linux-x86-64-4.0.10/bin:$PATH


# -----maya
# export PYTHONPATH=${LCTOOLSET}/applications/maya/scripts:$LCTOOLSET/applications/maya/2017-x64/scripts:/mnt/utility/lca_rig:$PYTHONPATH
# export MAYA_SCRIPT_PATH=${LCTOOLSET}/applications/maya/scripts:$MAYA_SCRIPT_PATH
# export MAYA_PLUG_IN_PATH=${LCTOOLSET}/applications/maya/2017-x64/plugins:$MAYA_PLUG_IN_PATH
# export MAYA_SHELF_PATH=${LCTOOLSET}/applications/maya/shelves:$MAYA_SHELF_PATH


# ------mtoa
export MTOA_HOME=${LCA_DEVMY_PATH}/arnold/mtoa-1.4.1.2-2017
export MAYA_MODULE_PATH=$MTOA_HOME
export MAYA_RENDER_DESC_PATH=$MTOA_HOME
export PYTHONPATH=${MTOA_HOME}/scripts:$PYTHONPATH
export solidangle_LICENSE=6053@10.0.0.5

# ------yeti
# export YETI_HOME=${LCA_DEVMY_PATH}/yeti/yeti-v2.2.0b02-2017
# export MAYA_MODULE_PATH=${YETI_HOME}:$MAYA_MODULE_PATH
# export MAYA_SCRIPT_PATH=${YETI_HOME}/scripts:$MAYA_SCRIPT_PATH
# export YETI_DOCS=${YETI_HOME}/docs
# export ARNOLD_PLUGIN_PATH=${YETI_HOME}/bin:$YETI_HOME/plug-ins:$ARNOLD_PLUGIN_PATH
# export LD_LIBRARY_PATH=${YETI_HOME}/bin:$LD_LIBRARY_PATH
# export MTOA_EXTENSIONS_PATH=${YETI_HOME}/plug-ins:$MTOA_EXTENSIONS_PATH
# export MTOA_PROCEDURAL=${YETI_HOME}/bin:$MTOA_PROCEDURAL
# export PYTHONPATH=${YETI_HOME}/scripts:$PYTHONPATH
# export PATH=${YETI_HOME}/bin:$PATH
# export peregrinel_LICENSE=5059@10.0.0.5
# export YETI_TMP=/home/yeti_cache


# ------xgen
export LD_LIBRARY_PATH=${MAYA_HOME}/plug-ins/xgen/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${MAYA_HOME}/lib:${LD_LIBRARY_PATH}
export LD_LIBRARY_PATH=${MTOA_HOME}/procedurals:${LD_LIBRARY_PATH}
export XGEN_LOCATION=${MAYA_HOME}/plug-ins/xgen
export XGEN_CONFIG_PATH=${MAYA_HOME}/plug-ins/xgen

# ------qualoth
# export MAYA_PLUG_IN_PATH=${LCA_DEVMY_PATH}/qualoth/qualoth-4.2-8/bin:$MAYA_PLUG_IN_PATH
# export MAYA_SCRIPT_PATH=${LCA_DEVMY_PATH}/qualoth/qualoth-4.2-8/script:$MAYA_SCRIPT_PATH
# export QUALOTH_SERVER=10.0.0.5
# export FXGEAR_SERVER=10.0.0.5
# export FXLM_IPADDR=10.0.0.5

# ------USD
# export USD_INSTALL_ROOT=${LCA_DEVUSD_PATH}/lca_usd_house/usd_centos_v080
# export MAYA_PLUG_IN_PATH=${USD_INSTALL_ROOT}/third_party/maya/plugin/:$MAYA_PLUG_IN_PATH
# export MAYA_SCRIPT_PATH=${USD_INSTALL_ROOT}/third_party/maya/share/usd/plugins/usdMaya/resources/:$MAYA_SCRIPT_PATH
# export PYTHONPATH=${USD_INSTALL_ROOT}/lib/python/:$PYTHONPATH
# export XBMLANGPATH=${USD_INSTALL_ROOT}/third_party/maya/share/usd/plugins/usdMaya/resources/:XBMLANGPATH
# source "/mnt/work/software/develop/maya/launcher/env_config/maya2017_dev.sh"

/mnt/usr/autodesk/maya2017update3/bin/maya2017 $@
