// Copyright (c) 2016 The Foundry Visionmongers Ltd.
#ifndef KATANA_FNSCENEGRAPHITERATOR_FNSCENEGRAPHITERATORAPI_H_
#define KATANA_FNSCENEGRAPHITERATOR_FNSCENEGRAPHITERATORAPI_H_

#if defined(_WIN32)
#  if defined(FNSCENEGRAPHITERATOR_APIEXPORT)
#    define FNSCENEGRAPHITERATOR_API __declspec(dllexport)
#  elif !defined(FNSCENEGRAPHITERATOR_STATIC)
#    define FNSCENEGRAPHITERATOR_API __declspec(dllimport)
#  else
#    define FNSCENEGRAPHITERATOR_API
#  endif  // FNSCENEGRAPHITERATOR_APIEXPORT

#elif defined(FNSCENEGRAPHITERATOR_APIEXPORT)
#  define FNSCENEGRAPHITERATOR_API __attribute__((visibility("default")))
#else
#  define FNSCENEGRAPHITERATOR_API
#endif  // _WIN32

#endif  // KATANA_FNSCENEGRAPHITERATOR_FNSCENEGRAPHITERATORAPI_H_
