# ********************************************************************
# This file contains copyrighted work from The Foundry,
# Sony Pictures Imageworks and Pixar, is intended for
# Katana and PRMan customers, and is not for distribution
# outside the terms of the corresponding EULA(s).
# ********************************************************************

all:
	cd KatanaProcedural; make
	cd DisplayDriver; make
	cd MultiresDisplayDriver; make
	cd ScenegraphLocationDelegatePlugins; make

clean:
	cd KatanaProcedural; make clean
	cd DisplayDriver; make clean
	cd MultiresDisplayDriver; make clean
	cd ScenegraphLocationDelegatePlugins; make clean

